-- Changed from uppercase to lowercase format for ease of handling
SELECT 
  patientunitstayid,
  ANIONGAP_min AS aniongap_min,
  ANIONGAP_max AS aniongap_max,
  ALBUMIN_min AS albumin_min,
  ALBUMIN_max AS albumin_max,
  BANDS_min AS bands_min,
  BANDS_max AS bands_max,
  BICARBONATE_min AS bicarbonate_min,
  BICARBONATE_max AS bicarbonate_max,
  HCO3_min AS hco3_min,
  HCO3_max AS hco3_max,
  BILIRUBIN_min AS bilirubin_min,
  BILIRUBIN_max AS bilirubin_max,
  CREATININE_min AS creatinine_min,
  CREATININE_max AS creatinine_max,
  CHLORIDE_min AS chloride_min,
  CHLORIDE_max AS chloride_max,
  GLUCOSE_min AS glucose_min,
  GLUCOSE_max AS glucose_max,
  HEMATOCRIT_min AS hematocrit_min,
  HEMATOCRIT_max AS hematocrit_max,
  HEMOGLOBIN_min AS hemoglobin_min,
  HEMOGLOBIN_max AS hemoglobin_max,
  LACTATE_min AS lactate_min,
  LACTATE_max AS lactate_max,
  PLATELET_min AS platelet_min,
  PLATELET_max AS platelet_max,
  POTASSIUM_min AS potassium_min,
  POTASSIUM_max AS potassium_max,
  PTT_min AS ptt_min,
  PTT_max AS ptt_max,
  INR_min AS inr_min,
  INR_max AS inr_max,
  PT_min AS pt_min,
  PT_max AS pt_max,
  SODIUM_min AS sodium_min,
  SODIUM_max AS sodium_max,
  BUN_min AS bun_min,
  BUN_max AS bun_max,
  WBC_min AS wbc_min,
  WBC_max AS wbc_max
FROM 
  `physionet-data.eicu_crd_derived.labsfirstday`
