---
title: "03_tables"
output: html_document
---

# Environment
```{r}
library(tableone)
library(kableExtra)
library(knitr)
library(ggplot2)
library(ggdist)
library(diagram)
library(DiagrammeR)
```


# Table one
```{r}
# # Lists the variables we are going to be including in table1
vars_in_table1 <- names(final_df_selected %>% select(age_numeric,gender,max_apachescore,apacheadmissiondx, icu_los_hours,norepinephrine_mean, norepinephrine_max, norepinephrine_min, epinephrine_mean, epinephrine_max, epinephrine_min, dopamine_mean, dopamine_max, dopamine_min, dobutamine_mean, dobutamine_max, dobutamine_min, phenylephrine_mean, phenylephrine_max, phenylephrine_min, vasopressin_mean, vasopressin_max, vasopressin_min, milrinone_mean, milrinone_max, milrinone_min, heparin_mean, heparin_max, heparin_min, warfarin_mean, warfarin_max, warfarin_min, heartrate_mean, heartrate_max, heartrate_min, respiratoryrate_mean, respiratoryrate_max, respiratoryrate_min, spo2_mean, spo2_max, spo2_min, nibp_systolic_mean, nibp_systolic_max, nibp_systolic_min, nibp_diastolic_mean, nibp_diastolic_max, nibp_diastolic_min, nibp_mean_mean, nibp_mean_max, nibp_mean_min, temperature_mean, temperature_max,temperature_min,aniongap_min,aniongap_max,albumin_min,albumin_max,bands_min,bands_max,bicarbonate_min,bicarbonate_max,hco3_min,hco3_max,bilirubin_min,bilirubin_max,creatinine_min,creatinine_max,chloride_min,chloride_max,glucose_min,glucose_max,hematocrit_min,hematocrit_max,hemoglobin_min,hemoglobin_max,lactate_min,lactate_max,platelet_min,platelet_max,potassium_min,potassium_max,ptt_min,ptt_max,inr_min,inr_max,pt_min,pt_max,sodium_min,sodium_max,bun_min,bun_max,wbc_min,wbc_max, icu_mortality_72hrs))

gender <- factor(final_df_selected$gender.x)
# Creates a dataset with only selected variables using our original dataset and generates an empty list for storing categorical variables
table1_dataset <- final_df_selected[,vars_in_table1]
cat_variables <- rep(NA, length(vars_in_table1))
stratifyby <- "icu_mortality_72hrs"

# Detects whether a variable is categorical or not
cont<-1
for (i in 1:length(vars_in_table1) ) {
  if ( n_distinct(table1_dataset[vars_in_table1[i] ]) <= 10 ) {
    print(i)
    print(vars_in_table1[i])
    print(names(table1_dataset[vars_in_table1[i]]))
    cat_variables[cont]<-names(table1_dataset[vars_in_table1[i]])
    cont<-cont+1
  }
}
cat_variables <- cat_variables[!is.na(cat_variables)]
table1_base <- print(CreateTableOne(vars = vars_in_table1
                                   , strata = stratifyby
                                  , factorVars = cat_variables
    ,data = table1_dataset, addOverall=T),varLabels = T)

# Run this in console for html output, the code below uses kableExtra::
starification_cats<-n_distinct(table1_dataset[,stratifyby])
 
# For console
table1_base %>%
   kbl(caption = "Table 1 of base model: Mortality 72 hours" , align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "No", "Yes", "", ""))
 
# Export kable
table1_base %>%
   kbl(caption = "Table 1 of base model: Mortality 72 hours" , align = "c") %>%
   kable_classic_2(full_width = F, html_font = "Cambria") %>%
   add_header_above(c("", "", "No", "Yes", "", "")) %>%
   save_kable("C:/Users/cjimenez10J/Documents/projects/eicu_mort_72h/figures/table1_base.html", zoom = 10)
```

#Creation of exclusion criteria diagram
```{r}
#Crea un lienzo vacío para el diagrama de flujo y definición de características globales para el gráfico que especifica la dirección de flujo de arriba a bajo
grViz("
      digraph {
      layout = neato;  // Cambia la disposición del grafo si lo deseas
      rankdir = TB;  // Establece la dirección de arriba a abajo
      }
    ")
#Agrego Nodos y conexiones (usa sintaxis DOT) 
graph <- grViz("
               digraph {
               layout = neato;
               rankdir = TB;
               A [label = 'Initial number of patients
               (n=200764)']
               
               B [label = 'EXCLUSION CRITERIA:
               Age < 16 years']
               
               C [label = 'Final number of patients
               (n=200468']
               
               A -> B
               B -> C
               }
               ")
graph
```



